development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "5892cda48eb90412acdb0e117127c0c9a290a48ddfa408c4e6713d45bb60b2e1"
  signature_expiration: 3600 # one hour
